### ISSUE TITLE
Translation issue with quote

### ISSUE THREAD

**Issue by dariof28** [KingWu/gen_lang#2]
Declaring a string that contains ' (for example l'aggiornamento) the resulting generation will contains double quotes.

Futhermore if you insert a \n the resulting string will be broken because in the generated file the \n breaks the line (it's not kept inside the text) and the string it's splitted into 2 strings and this results in a broken file that cannot be compiled

Possible solution: use double quote when initialize the string object in the generated file

**Comment by KingWu** [comment]
Fixed this issue. Released v0.1.2
